// Code copied from https://github.com/SentiOne/react-bootstrap-daterangepicker private repository

"use strict";
/* generated by gulpfile.js */
module.exports = exports = function () {
  return [
    "<input>",
    "alwaysShowCalendars",
    "applyClass",
    "autoApply",
    "autoUpdateInput",
    "buttonClasses",
    "cancelClass",
    "dateLimit",
    "dateRange",
    "drops",
    "endDate",
    "isCustomDate",
    "isInvalidDate",
    "linkedCalendars",
    "locale",
    "maxDate",
    "minDate",
    "opens",
    "parentEl",
    "ranges",
    "showCustomRangeLabel",
    "showDropdowns",
    "showISOWeekNumbers",
    "showWeekNumbers",
    "singleDatePicker",
    "startDate",
    "template",
    "timePicker",
    "timePicker24Hour",
    "timePickerIncrement",
    "timePickerSeconds"
  ];
};